# Uncomment this line to define a global platform for your project

platform :ios, ‘8.0'
source ‘https://github.com/CocoaPods/Specs.git'
use_frameworks!

target "LeakSmart" do

pod 'IQKeyboardManager'
pod 'PureLayout'
pod 'M13Checkbox'
pod 'iOS-Slide-Menu'
end